# Change baseurl before deploy
baseurl = "http://wheel"
# languageCode = "en-us"
paginate = 10
title = "玽琅小说家"

# Theme i18n support
# Available values: en, fr, id, ja, ko, pt-br, zh-cn, zh-tw, es, de, nl, it, th, el, uk, ar
defaultContentLanguage = "zh-cn"

# Set hasCJKLanguage -0 true if DefaultContentLanguage is in [zh-cn ja ko]
# This will make .Summary and .WordCount behave correctly for CJK languages.
hasCJKLanguage = true

# Change it to your Disqus shortname before using
#disqusShortname = "gainovel"