# Rename this file to languages.toml to enable multilingual support
[zh-cn]
languageName = "简体中文"
languagedirection = "ltr"
title = "玽琅小说家"
weight = 1

[en]
languageName = "English"
languagedirection = "ltr"
title = "gainovel"
weight = 2
